# Set the enviroment on IFCA
ulimit -l unlimited
ulimit -s unlimited
module load wrflibs_spack/compiler/intel-classic-2021.10.0
module load wrflibs_spack/netcdf-c/4.9.2-intel-oneapi-mpi-2021.11.0-intel-2021.10.0
module load wrflibs_spack/netcdf-fortran/4.6.1-intel-oneapi-mpi-2021.11.0-intel-2021.10.0

